api:
  image: kathirganesan/books-api
  tag: latest
  replicaCount: 1

ui:
  image: kathirganesan/books-ui
  tag: latest
  replicaCount: 1

ingress:
  enabled: true
  ingressClassName: nginx
  host: books.zenflixapp.online
  tls: true
  tlsSecret: books-app-tls

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""