apiVersion: v1
kind: Service
metadata:
  name: books-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: books-api
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: books-ui
spec:
  type: {{ .Values.service.type }}
  selector:
    app: books-ui
  ports:
    - port: 80
      targetPort: 80